// Smoky Plum Night — Quickshell QML theme singleton
// Generated from tokens/smoky-plum.tokens.json v0.1.0; do not edit by hand.
//
// Usage:
//   Register this file as a QML singleton in your qmldir, then:
//   import Smth 1.0
//   color: SmokyPlumTheme.baseBackground
pragma Singleton
import QtQuick

QtObject {
    readonly property color baseBackground: "#0A0B12"
    readonly property color baseSidebar: "#19141E"
    readonly property color baseEditor: "#120F17"
    readonly property color basePanel: "#110D16"
    readonly property color atmosphereGlow: "#402F48"
    readonly property color atmosphereDepth: "#1A1520"
    readonly property color borderDefault: "#4A385A"
    readonly property color borderSubtle: "#31263C"
    readonly property color borderStrong: "#5A466E"
    readonly property color borderFocus: "#FF4A74"
    readonly property color textPrimary: "#FAF0E6"
    readonly property color textSecondary: "#BEB6B0"
    readonly property color textMuted: "#8F8987"
    readonly property color textDisabled: "#6A6466"
    readonly property color textInverse: "#0A0B12"
    readonly property color textOnAccent: "#140A10"
    readonly property color accentRose: "#FF4A74"
    readonly property color accentCool: "#E9DDFF"
    readonly property color highlightBackground: "#2A1F3F"
    readonly property color highlightBorder: "#5A466E"
    readonly property color surfaceHover: "#1A1525"
    readonly property color surfaceActive: "#20192F"
    readonly property color surfaceSelected: "#2A1F3F"
    readonly property color surfaceElevated: "#19141E"
    readonly property color surfaceSunken: "#0A0B12"
    readonly property color surfaceOverlay: "#1E1727"
    readonly property color selectionBackground: "#4C2647"
    readonly property color selectionForeground: "#FAF0E6"
    readonly property color selectionBorder: "#82476F"
    readonly property color cursorDefault: "#E9DDFF"
    readonly property color cursorAccent: "#FF4A74"
    readonly property color shadowColor: Qt.rgba(0.0000, 0.0000, 0.0000, 0.5020)
    readonly property color syntaxComment: "#8F8987"
    readonly property color syntaxPunctuation: "#BEB6B0"
    readonly property color syntaxOperator: "#BEB6B0"
    readonly property color syntaxKeyword: "#FF4A74"
    readonly property color syntaxControl: "#FF4A74"
    readonly property color syntaxStorage: "#FF4A74"
    readonly property color syntaxIdentifier: "#E9DDFF"
    readonly property color syntaxFunction: "#ECE0FB"
    readonly property color syntaxMethod: "#ECE0FB"
    readonly property color syntaxProperty: "#CBBFD0"
    readonly property color syntaxType: "#EADFFD"
    readonly property color syntaxClass: "#EADFFD"
    readonly property color syntaxString: "#D4CAD9"
    readonly property color syntaxNumber: "#FE7C96"
    readonly property color syntaxBoolean: "#FE6F8D"
    readonly property color syntaxConstant: "#FE7C96"
    readonly property color syntaxRegex: "#F77FA6"
    readonly property color syntaxEscape: "#FF4A74"
    readonly property color syntaxDeprecated: "#6A6466"
    readonly property color diagnosticError: "#FF6B8A"
    readonly property color diagnosticWarning: "#DDB879"
    readonly property color diagnosticSuccess: "#9BCB9D"
    readonly property color diagnosticInfo: "#C9B7FF"
    readonly property color diagnosticHint: "#D7CDF5"
    readonly property color diagnosticErrorBackground: "#361923"
    readonly property color diagnosticWarningBackground: "#30251B"
    readonly property color diagnosticSuccessBackground: "#1F2A20"
    readonly property color diagnosticInfoBackground: "#252033"
    readonly property color vcsAdded: "#9BCB9D"
    readonly property color vcsModified: "#BBA6F6"
    readonly property color vcsDeleted: "#FF6B8A"
    readonly property color vcsRenamed: "#E9DDFF"
    readonly property color vcsIgnored: "#6A6466"
    readonly property color terminalBlack: "#0A0B12"
    readonly property color terminalRed: "#FF6B8A"
    readonly property color terminalGreen: "#9BCB9D"
    readonly property color terminalYellow: "#DDB879"
    readonly property color terminalBlue: "#B7A3FF"
    readonly property color terminalMagenta: "#FF4A74"
    readonly property color terminalCyan: "#B9D7D2"
    readonly property color terminalWhite: "#FAF0E6"
    readonly property color terminalBrightBlack: "#6A5580"
    readonly property color terminalBrightRed: "#FF8AA1"
    readonly property color terminalBrightGreen: "#B2E1B1"
    readonly property color terminalBrightYellow: "#EAC891"
    readonly property color terminalBrightBlue: "#E9DDFF"
    readonly property color terminalBrightMagenta: "#FF6F96"
    readonly property color terminalBrightCyan: "#D0EEE9"
    readonly property color terminalBrightWhite: "#FFFFFF"
    readonly property color buttonPrimaryBackground: "#FF4A74"
    readonly property color buttonPrimaryHoverBackground: "#FF638B"
    readonly property color buttonPrimaryForeground: "#140A10"
    readonly property color buttonSecondaryBackground: "#20192F"
    readonly property color buttonSecondaryForeground: "#FAF0E6"
    readonly property color inputBackground: "#110D16"
    readonly property color inputBorder: "#31263C"
    readonly property color inputPlaceholder: "#8F8987"
    readonly property color tabActiveBackground: "#120F17"
    readonly property color tabActiveForeground: "#FF4A74"
    readonly property color tabInactiveBackground: "#110D16"
    readonly property color tabInactiveForeground: "#BEB6B0"
    readonly property color sidebarBackground: "#19141E"
    readonly property color sidebarForeground: "#BEB6B0"
    readonly property color sidebarActiveForeground: "#FAF0E6"
    readonly property color sidebarActiveBackground: "#20192F"
    readonly property color statusbarBackground: "#0A0B12"
    readonly property color statusbarForeground: "#BEB6B0"
    readonly property color statusbarActiveForeground: "#FF4A74"
    readonly property color badgeBackground: "#20192F"
    readonly property color badgeForeground: "#E9DDFF"
}
